inherit_from: .rubocop_todo.yml
require: rubocop-rails

AllCops:
  Exclude:
    - 'db/**/*.rb'
    - 'config/**/*.rb'
    - 'bin/bundle'
    - 'spec/rails_helper.rb'

Layout/SpaceInsideArrayLiteralBrackets: 
  EnforcedStyle: no_space

Layout/SpaceInsideBlockBraces:
  EnforcedStyle: space

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  EnforcedStyle: brackets